/*
Copyright 2017 The Caicloud sample-controller Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	resourceclass_v1alpha1 "github.com/caicloud/resource-controller/pkg/apis/resourceclass/v1alpha1"
	versioned "github.com/caicloud/resource-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/caicloud/resource-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/caicloud/resource-controller/pkg/client/listers/resourceclass/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ResourceClassInformer provides access to a shared informer and lister for
// ResourceClasses.
type ResourceClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ResourceClassLister
}

type resourceClassInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewResourceClassInformer constructs a new informer for ResourceClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourceClassInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ResourceclassV1alpha1().ResourceClasses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ResourceclassV1alpha1().ResourceClasses(namespace).Watch(options)
			},
		},
		&resourceclass_v1alpha1.ResourceClass{},
		resyncPeriod,
		indexers,
	)
}

func defaultResourceClassInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewResourceClassInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *resourceClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&resourceclass_v1alpha1.ResourceClass{}, defaultResourceClassInformer)
}

func (f *resourceClassInformer) Lister() v1alpha1.ResourceClassLister {
	return v1alpha1.NewResourceClassLister(f.Informer().GetIndexer())
}
